# Generated by Django 5.2.13 on 2026-04-23 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.jobcategory'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], default='FULL_TIME', max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('NO_EXPERIENCE', 'No Experience'), ('JUNIOR', 'Junior (1-3 years)'), ('MID_LEVEL', 'Mid-Level (3-5 years)'), ('SENIOR', 'Senior (5+ years)'), ('LEAD', 'Lead / Manager')], default='MID_LEVEL', max_length=32),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
        migrations.CreateModel(
            name='SavedVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'JOB_SEEKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='vacancies.vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'vacancy'), name='unique_saved_vacancy')],
            },
        ),
    ]
